/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzarendeles;

import javax.swing.JOptionPane;

/**
 *
 * @author HalászGergő(SZOFT_20
 */
public class Pizzarendeles extends javax.swing.JFrame {

    /**
     * Creates new form Pizzarendeles
     */
    public Pizzarendeles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btngrpMeret = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbnOlaszkolbasz = new javax.swing.JRadioButton();
        rbnAnanasz = new javax.swing.JRadioButton();
        lblTesztak = new javax.swing.JLabel();
        lblFeltet = new javax.swing.JLabel();
        lblMeret = new javax.swing.JLabel();
        rbnSonka = new javax.swing.JRadioButton();
        cmbMeret = new javax.swing.JComboBox<>();
        cmbTeszta = new javax.swing.JComboBox<>();
        btnMegrendeles = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMegjegyzes = new javax.swing.JTextArea();
        lblMegjegyzes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTelefon = new javax.swing.JLabel();
        lblNev = new javax.swing.JLabel();
        lblVaros = new javax.swing.JLabel();
        lblCim = new javax.swing.JLabel();
        txtNev = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtVaros = new javax.swing.JTextField();
        txtCim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblUdito = new javax.swing.JLabel();
        cmbUdito = new javax.swing.JComboBox<>();
        lblmennyiseg = new javax.swing.JLabel();
        spnMennyiseg = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        btnKeszpenz = new javax.swing.JRadioButton();
        btnBank = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzaválogató");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Rakd össze a saját pizzád!");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        rbnOlaszkolbasz.setText("Olaszkolbász");
        rbnOlaszkolbasz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        rbnAnanasz.setText("Ananász");
        rbnAnanasz.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblTesztak.setText("Tészták:");

        lblFeltet.setText("Feltétek:");

        lblMeret.setText("Méret:");

        rbnSonka.setText("Sonka");
        rbnSonka.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cmbMeret.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válassz méretet", "28 cm", "32 cm", "45 cm" }));
        cmbMeret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMeretActionPerformed(evt);
            }
        });

        cmbTeszta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válassz tésztát", "Normál", "Gluténmentes", "Cukormentes", "Fittness" }));
        cmbTeszta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTesztaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFeltet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbnSonka)
                        .addGap(31, 31, 31)
                        .addComponent(rbnOlaszkolbasz)
                        .addGap(18, 18, 18)
                        .addComponent(rbnAnanasz)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMeret)
                        .addGap(21, 21, 21)
                        .addComponent(cmbMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTesztak)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTeszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMeret)
                    .addComponent(cmbMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTesztak)
                    .addComponent(cmbTeszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnAnanasz)
                    .addComponent(rbnOlaszkolbasz)
                    .addComponent(rbnSonka)
                    .addComponent(lblFeltet))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMegrendeles.setBackground(new java.awt.Color(255, 0, 0));
        btnMegrendeles.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        btnMegrendeles.setForeground(new java.awt.Color(255, 255, 255));
        btnMegrendeles.setText("MEGRENDELÉS");
        btnMegrendeles.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnMegrendeles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMegrendeles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegrendelesActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtMegjegyzes.setColumns(20);
        txtMegjegyzes.setRows(3);
        txtMegjegyzes.setTabSize(6);
        jScrollPane1.setViewportView(txtMegjegyzes);

        lblMegjegyzes.setText("Megjegyzés a futárnak:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMegjegyzes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblMegjegyzes)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTelefon.setText("Telefonszám:");

        lblNev.setText("Név:");

        lblVaros.setText("Város:");

        lblCim.setText("Utca, házszám:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefon)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblNev)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtNev, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCim)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblVaros)
                        .addGap(24, 24, 24)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtVaros, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(txtCim))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNev)
                    .addComponent(lblVaros)
                    .addComponent(txtNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVaros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(lblCim)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/pizza.png"))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblUdito.setText("Üdítő:");

        cmbUdito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válassz egy üdítőt!", "Coca-Cola", "Pepsi", "Fanta", "Sprite", "7UP", "Narancslé", "Limonádé" }));
        cmbUdito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUditoActionPerformed(evt);
            }
        });

        lblmennyiseg.setText("Pizzák mennyisége:");

        spnMennyiseg.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmennyiseg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnMennyiseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblUdito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbUdito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUdito)
                    .addComponent(cmbUdito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblmennyiseg)
                    .addComponent(spnMennyiseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup3.add(btnKeszpenz);
        btnKeszpenz.setText("Készpénz");

        buttonGroup3.add(btnBank);
        btnBank.setText("Bankkártya");

        jLabel3.setText("Fizetés módja:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(47, 47, 47)
                .addComponent(btnKeszpenz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnBank)
                .addGap(43, 43, 43))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnKeszpenz)
                    .addComponent(btnBank))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(129, 129, 129))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnMegrendeles, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel1, jPanel2, jPanel3, jPanel4, jPanel5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnMegrendeles, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMegrendelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegrendelesActionPerformed
       String uzenet = "Biztos, hogy megrendeled?";
       String cim = "MEGRENDELÉS MEGERŐSÍTÉSE";
       String osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";
       
       boolean MeretValasztva = cmbMeret.getSelectedIndex() > 0;
       boolean TesztaValasztva = cmbTeszta.getSelectedIndex() > 0;
       boolean UditoValasztva = cmbUdito.getSelectedIndex() > 0;
       if(rbnSonka.isSelected()){
                   osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+rbnSonka.getText()+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";

        if(rbnOlaszkolbasz.isSelected()){
                osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+rbnSonka.getText()+", "+rbnOlaszkolbasz.getText()+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";
                if(rbnAnanasz.isSelected()){
                osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+rbnSonka.getText()+", "+rbnAnanasz.getText()+", "+rbnOlaszkolbasz.getText()+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";

        }
        }
        
       }
       if(rbnOlaszkolbasz.isSelected()){
                osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+rbnOlaszkolbasz.getText()+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";
                
                if(rbnSonka.isSelected()){
                osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+rbnSonka.getText()+", "+rbnOlaszkolbasz.getText()+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";
                  if(rbnAnanasz.isSelected()){
                osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+rbnSonka.getText()+", "+rbnAnanasz.getText()+", "+rbnOlaszkolbasz.getText()+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";
        }
        }
       }
       if(rbnAnanasz.isSelected()){
                osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+rbnAnanasz.getText()+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";
                if(rbnOlaszkolbasz.isSelected()){
                osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+rbnAnanasz.getText()+", "+rbnOlaszkolbasz.getText()+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";

                }
                if(rbnSonka.isSelected()){
                osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+rbnSonka.getText()+", "+rbnAnanasz.getText()+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";
                  if(rbnOlaszkolbasz.isSelected()){
                osszegzo = (String) "Rendelésed összesítője: "+"\nNév: "+txtNev.getText()+"\nVáros: "+txtVaros.getText()+"\nTelefonszám: "+txtTelefon.getText()+"\nUtca, házszám: "+txtCim.getText()+"\nMéret: "+cmbMeret.getSelectedItem()+"\nTészta: "+cmbTeszta.getSelectedItem()+"\nFeltétek: "+rbnSonka.getText()+", "+rbnAnanasz.getText()+", "+rbnOlaszkolbasz.getText()+"\nÜditő: "+cmbUdito.getSelectedItem()+"\nA pizza összege 1500Ft";
        }
        }
       }

       
       
       if(MeretValasztva){
       }else{
        osszegzo = "Nincs méret választva";
       }
       if(TesztaValasztva){
       }else{
        osszegzo = "Nincs tészta választva";
       }
       if(UditoValasztva){
       }else{
        osszegzo = "Nincs üditő választva";
       }
       JOptionPane.showMessageDialog(rootPane, osszegzo, cim, 2);
    }//GEN-LAST:event_btnMegrendelesActionPerformed

    private void cmbMeretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMeretActionPerformed
        String meret = (String) "A kiválasztott méreted: "+cmbMeret.getSelectedItem();
        String meretcim = "FIGYELEM!";
        JOptionPane.showMessageDialog(rootPane, meret, meretcim, 1);
    }//GEN-LAST:event_cmbMeretActionPerformed

    private void cmbTesztaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTesztaActionPerformed
        String teszta = (String) "A kiválasztott tésztád: "+cmbTeszta.getSelectedItem();
        String tesztacim = "FIGYELEM!";
        JOptionPane.showMessageDialog(rootPane, teszta, tesztacim, 1);
    }//GEN-LAST:event_cmbTesztaActionPerformed

    private void cmbUditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUditoActionPerformed
        String udito = (String) "A kiválasztott üditőd: "+cmbUdito.getSelectedItem();
        String uditocim = "FIGYELEM!";
        JOptionPane.showMessageDialog(rootPane, udito, uditocim, 1);
    }//GEN-LAST:event_cmbUditoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzarendeles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnBank;
    private javax.swing.JRadioButton btnKeszpenz;
    private javax.swing.JButton btnMegrendeles;
    private javax.swing.ButtonGroup btngrpMeret;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmbMeret;
    private javax.swing.JComboBox<String> cmbTeszta;
    private javax.swing.JComboBox<String> cmbUdito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCim;
    private javax.swing.JLabel lblFeltet;
    private javax.swing.JLabel lblMegjegyzes;
    private javax.swing.JLabel lblMeret;
    private javax.swing.JLabel lblNev;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTesztak;
    private javax.swing.JLabel lblUdito;
    private javax.swing.JLabel lblVaros;
    private javax.swing.JLabel lblmennyiseg;
    private javax.swing.JRadioButton rbnAnanasz;
    private javax.swing.JRadioButton rbnOlaszkolbasz;
    private javax.swing.JRadioButton rbnSonka;
    private javax.swing.JSpinner spnMennyiseg;
    private javax.swing.JTextField txtCim;
    private javax.swing.JTextArea txtMegjegyzes;
    private javax.swing.JTextField txtNev;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextField txtVaros;
    // End of variables declaration//GEN-END:variables
}
